# Traefik dynamic configuration file
# Specifically for TLS settings
tls:
  certificates:
  - certFile: /certificates/{{ env "KME" }}/rest/rest.ca-chain.cert.pem
    keyFile: /certificates/{{ env "KME" }}/rest/rest.key.pem
    stores:
    - default
#  - certFile: /certificates/kme1/rest/rest.ca-chain.cert.pem
#    keyFile: /certificates/kme1/rest/rest.key.pem
#    stores:
#    - default
#  - certFile: /certificates/kme2/rest/rest.ca-chain.cert.pem
#    keyFile: /certificates/kme2/rest/rest.key.pem
#    stores:
#    - default
  options:
    default:
      minVersion: VersionTLS12
      maxVersion: VersionTLS13
      sniStrict: True
      preferServerCipherSuites: True
      clientAuth:
        caFiles:
        - /certificates/kme1/vault_init/vault_init.ca-chain.cert.pem
#        - /certificates/kme2/vault_init/vault_init.ca-chain.cert.pem
        clientAuthType: RequireAndVerifyClientCert
  stores:
    default:
      defaultCertificate:
        certFile: /certificates/{{ env "KME" }}/rest/rest.ca-chain.cert.pem
        keyFile: /certificates/{{ env "KME" }}/rest/rest.key.pem
