
Skip to content
Pull requests
Issues
Marketplace
Explore
@syed82ab
s-fifteen-instruments /
qcrypto
Public
forked from kurtsiefer/qcrypto

1
0

    10

Code
Pull requests
Actions
Projects
Wiki
Security
Insights

    Settings

qcrypto/.readthedocs.yaml
@syed82ab
syed82ab Update .readthedocs.yaml
Latest commit a7743a2 4 days ago
History
1 contributor
29 lines (25 sloc) 742 Bytes
# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
    # You can also specify other tool versions:
    # nodejs: "16"
    # rust: "1.55"
    # golang: "1.17"

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
      
# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/source/conf.py
   fail_on_warning: true
# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
   - pdf

# Optionally declare the Python requirements required to build your docs
# python:
#    install:
#    - requirements: docs/requirements.txt
