# Guardian is a quantum key distribution REST API and supporting software stack.
# Copyright (C) 2021  W. Cyrus Proctor
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
version: "3.7"

services:

  certauth: &certauth_label
    build: 
      context: ./
      dockerfile: ./certauth/Dockerfile
    working_dir: /certificates/generation
    env_file:
      - common/log.env
    # WARNING:
    # Entrypoint is set to "make"; only 'make clean' to remove
    # and rebuild root and intermediate certificate authorities
    command: ["make clean && export LOCAL_KME_ID=${LOCAL_KME_ID:-SETMEINMAKEFILE} && make certs && make install"]
    networks:
      - internal-private
    volumes:
      - ./volumes/${LOCAL_KME_ID:-SETMEINMAKEFILE}/certificates:/certificates
        # Prevents erroneous creation of directory on init if file not present
      - type: bind
        source: ./common/CERTAUTH_SECRETS
        target: /SECRETS
      - type: bind
        source: ./common/CERTAUTH_CONFIG
        target: /CONFIG
      - type: bind
        source: ./common/kme-ca.cert.pem
        target: /kme-ca.cert.pem
      - type: bind
        source: ./common/kme-ca.key.pem
        target: /kme-ca.key.pem
      - type: bind
        source: ./common/full-chain.cert.pem
        target: /full-chain.cert.pem


  certauth_csr:
    <<: *certauth_label
    command: ["make csr"]

  vault: &vault_label
    # Use the latest Hashicorp Vault v1.7.x image available
    #image: vault:${VAULT_TAG:-latest}
    image: vault:1.7.3
    env_file:
      - common/log.env
    ports:
      # Listen on port 8200
      - 8200:8200
    cap_add:
      # With this priviledged Linux capability, the container will attempt to
      # lock memory to prevent sensitive values from being swapped to disk.
      - IPC_LOCK
    volumes:
      # Mount a volume that stores the Vault @file configurations
      - ./volumes/${LOCAL_KME_ID:-SETMEINMAKEFILE}/vault/config:/vault/config
      # Mount a volume that stores any persistent data
      - ./volumes/${LOCAL_KME_ID:-SETMEINMAKEFILE}/vault/data:/vault/data
      # Mount a volume to store persistent logs
      - ./volumes/${LOCAL_KME_ID:-SETMEINMAKEFILE}/vault/logs:/vault/logs
      # Mount a volume that stores the TLS certificates
      - ./volumes/${LOCAL_KME_ID:-SETMEINMAKEFILE}/certificates/production:/certificates
    # Server Configuration: /vault/config/vault-config.hcl
    command: ["server"]
    networks:
      # Use only the private internal network created by Docker to be shared
      # by any backend service that needs to communicate amongst internal services
      - internal-private

  vault_client_auth:
    <<: *vault_label
    ports:
      - 8282:8200
    entrypoint: ["/bin/sh", "-c"]
    command: ["/vault/config/client_auth.sh"]

  vault_init: &vault_init_label
    build:
      context: ./
      dockerfile: ./vault_init/Dockerfile
    environment:
      - LOCAL_KME_ID=${LOCAL_KME_ID:-SETMEINMAKEFILE}
      - REMOTE_KME_ID=${REMOTE_KME_ID:-SETMEINMAKEFILE}
      - LOCAL_SAE_ID=${LOCAL_SAE_ID:-SETMEINMAKEFILE}
      - REMOTE_SAE_ID=${REMOTE_SAE_ID:-SETMEINMAKEFILE}
      - LOCAL_KME_ADDRESS=${LOCAL_KME_ADDRESS:-SETMEINMAKEFILE}

    env_file:
      - common/log.env
    command: ["vault_init.py", "--first"]
    networks:
      - internal-private
    volumes:
      - ./volumes/${LOCAL_KME_ID:-SETMEINMAKEFILE}/certificates:/certificates
      - ./volumes/${LOCAL_KME_ID:-SETMEINMAKEFILE}/vault/policies:/vault/policies
      - type: bind
        source: ./common/global_config.py
        target: /root/code/global_config.py
      - type: bind
        source: ./common/vault_init_config.py
        target: /root/code/vault_init_config.py

  vault_init_phase_2:
    <<: *vault_init_label
    command: ["vault_init.py", "--second"]

  vault_clear:
    <<: *vault_init_label
    command: ["vault_init.py", "--clear"]

  qkd:
    build:
      context: ./
      dockerfile: ./qkd/Dockerfile
    environment:
      - LOCAL_KME_ID=${LOCAL_KME_ID:-SETMEINMAKEFILE}
      - REMOTE_KME_ID=${REMOTE_KME_ID:-SETMEINMAKEFILE}
    env_file:
      - common/log.env
    command: ["clean", "ctest"]
    networks:
      - internal-private
    volumes:
      # NOTE: Only kme1 generates epoch files in this configuration
      - ./volumes/${LOCAL_KME_ID:-SETMEINMAKEFILE}/qkd/epoch_files:/root/code/qsim/epoch_files
      - type: bind
        source: ./common/qkd_config
        target: /root/code/qsim/qkd_config

  notifier:
    build:
      context: ./
      dockerfile: ./notifier/Dockerfile
    env_file:
      - common/log.env
    command: ["notifier.py"]
    networks:
      - internal-private
    volumes:
      # NOTE: Only kme1 generates epoch files in this configuration
      - ./volumes/${LOCAL_KME_ID:-SETMEINMAKEFILE}/qkd/epoch_files/${REMOTE_KME_ID:-SETMEINMAKEFILE}:/epoch_files
      - type: bind
        source: ./common/global_config.py
        target: /root/code/global_config.py
      - type: bind
        source: ./common/notifier_config.py
        target: /root/code/notifier_config.py
 
  watcher:
    build:
      context: ./
      dockerfile: ./watcher/Dockerfile
    environment:
      - LOCAL_KME_ID=${LOCAL_KME_ID:-SETMEINMAKEFILE}
      - REMOTE_KME_ID=${REMOTE_KME_ID:-SETMEINMAKEFILE}
      - LOCAL_KME_ALT_ID=${LOCAL_KME_ALT_ID:-SETMEINMAKEFILE}
      - REMOTE_KME_ALT_ID=${REMOTE_KME_ALT_ID:-SETMEINMAKEFILE}
    env_file:
      - common/log.env
    command: ["watcher.py"]
    networks:
      - internal-private
    volumes:
      # NOTE: Only kme1 generates epoch files in this configuration
      - ./volumes/${LOCAL_KME_ID:-SETMEINMAKEFILE}/qkd/epoch_files/${REMOTE_KME_ID:-SETMEINMAKEFILE}:/epoch_files
      - ./volumes/${LOCAL_KME_ID:-SETMEINMAKEFILE}/qkd/digest_files/${REMOTE_KME_ID:-SETMEINMAKEFILE}:/digest_files
      - ./volumes/${LOCAL_KME_ID:-SETMEINMAKEFILE}/certificates:/certificates
      - type: bind
        source: ./common/global_config.py
        target: /root/code/global_config.py
      - type: bind
        source: ./common/watcher_config.py
        target: /root/code/watcher_config.py

  unsealer:
    build:
      context: ./
      dockerfile: ./unsealer/Dockerfile
    env_file:
      - common/log.env
    command: ["unsealer.py"]
    volumes:
      # Listen to the Docker Daemon through this socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Mount a volume that stores the TLS certificates
      - ./volumes/${LOCAL_KME_ID:-SETMEINMAKEFILE}/certificates/production:/certificates/production
      - type: bind
        source: ./common/global_config.py
        target: /root/code/global_config.py
      - type: bind
        source: ./common/unsealer_config.py
        target: /root/code/unsealer_config.py
    networks:
      # Use only the private internal network created by Docker to be shared
      # by any backend service that needs to communicate amongst internal services
      - internal-private


networks:

  # Use the private internal network created by Docker to be shared
  # by any backend service that needs to communicate amongst internal services
  internal-private:
    external: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.192.0/24
