#!/usr/bin/env bash
#
# Guardian is a quantum key distribution REST API and supporting software stack.
# Copyright (C) 2021  W. Cyrus Proctor
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#
# Pfind is used to find an initial timing offset between
# the HEC party (Alice) and the LEC party (Bob). This helps
# get timing information in syncrhonization enough to begin
# further key analysis.

set -x

export override=true
source qkd_config


# Find second common epoch
export start_epoch=`comm -12 <(ls ${hec_data_dir}/t1.hec) <(ls ${lec_data_dir}/t2.lec) | head -n 2 | tail -n 1`

echo "First common epoch: ${start_epoch}"

# Count the number of shared epochs
# Do not count the first or last shared epoch (-2)
export num_shared_epochs=$((`comm -12 <(ls ${hec_data_dir}/t1.hec) <(ls ${lec_data_dir}/t2.lec) | wc -l` - 2))

echo "Number of shared epochs: ${num_shared_epochs}"

if [ "${num_shared_epochs}" -le "0" ]; then
  echo "Error: Not enough shared epochs for pfind! Exiting."
  exit -1
fi

export timediff=`\
${base_dir}/pfind         \
-D ${hec_data_dir}/t1.hec \
-d ${lec_data_dir}/t2.lec \
-e "0x${start_epoch}"     \
-r 1                      \
-n ${num_shared_epochs}   \
-V 0                      \
-q 17 | tail -1`

echo "Time difference (1/8 nsec): ${timediff}"
echo "${timediff}" > ${data_dir}/timediff.out
