#!/usr/bin/env bash
#
# Guardian is a quantum key distribution REST API and supporting software stack.
# Copyright (C) 2021  W. Cyrus Proctor
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

# esim config settings
export           num_events=5E4       # Total number of events to simulate
export source_emission_rate=1E3       # Event rate [events/second]
export      lec_time_offset=1E0       # LEC party time offset [nanoseconds]
export        lec_loss_frac=0.0       # LEC Loss Fraction [0(no loss)<=fraction<=1(all loss)]
export           error_rate=0.0       # Simulated QBER [0<=fraction<=1]
export  relative_freq_drift=0.0

# error correction config settings
export ec_min_bits=1024               # minimal number of raw bits to process in error correction

# path config settings (recommend to not change)
export base_dir=${PWD}/../qcrypto/remotecrypto
export data_base_dir=${PWD}
export hec_data_dir=${data_base_dir}/hec
export lec_data_dir=${data_base_dir}/lec

if [ "${override:-x}" != "true" ]; then
  if [ "${#}" -lt 1 ]; then
    echo "Enter the Count Type (hec or lec)"
    exit -1
  fi
  
  export count_type=${1}
  
  if [ "${count_type}" = "hec" ]; then
    export data_dir=${hec_data_dir}
  elif [ "${count_type}" = "lec" ]; then
    export data_dir=${lec_data_dir}
  else
    echo "Unrecognized count type. (hec or lec)"
    exit -1
  fi

else

 export data_dir=${data_base_dir}

fi

