# Traefik dynamic configuration file
# Specifically for TLS settings
tls:
  certificates:
  - certFile: /certificates/{{ env "LOCAL_KME_ID" }}/rest/rest.ca-chain.cert.pem
    keyFile: /certificates/{{ env "LOCAL_KME_ID" }}/rest/rest.key.pem
    stores:
    - default
  - certFile: /certificates/{{ env "REMOTE_KME_ID" }}/rest/rest.ca-chain.cert.pem
    keyFile: /certificates/{{ env "REMOTE_KME_ID" }}/rest/rest.key.pem
    stores:
    - default
  options:
    default:
      minVersion: VersionTLS12
      maxVersion: VersionTLS13
      sniStrict: True
      preferServerCipherSuites: True
      clientAuth:
        caFiles:
        - /certificates/{{ env "LOCAL_KME_ID" }}/vault_init/vault_init.ca-chain.cert.pem
        - /certificates/{{ env "REMOTE_KME_ID" }}/vault_init/vault_init.ca-chain.cert.pem
        clientAuthType: RequireAndVerifyClientCert
  stores:
    default:
      defaultCertificate:
        certFile: /certificates/{{ env "LOCAL_KME_ID" }}/rest/rest.ca-chain.cert.pem
        keyFile: /certificates/{{ env "LOCAL_KME_ID" }}/rest/rest.key.pem
