# Traefik dynamic configuration file
# Specifically for TLS settings
http:
  routers:
    dashboard-http:
      rule: Host(`traefik.{{ env "LOCAL_KME_ID" }}`)
      entryPoints: web
      service: api@internal
    dashboard-https:
      rule: Host(`traefik.{{ env "LOCAL_KME_ID" }}`)
      entryPoints: websecure
      tls: True
      service: api@internal

tls:
  certificates:
    # KME server-side identity
  - certFile: /certificates/{{ env "LOCAL_KME_ID" }}/rest/rest.ca-chain.cert.pem
    keyFile: /certificates/{{ env "LOCAL_KME_ID" }}/rest/rest.key.pem
    stores:
    - default
  options:
    default:
      minVersion: VersionTLS12
      maxVersion: VersionTLS13
      sniStrict: True
      preferServerCipherSuites: True
      clientAuth:
        caFiles:
        # Allow clients from both KME CA chains
        - /certificates/{{ env "LOCAL_KME_ID" }}/rest/rest.ca-chain.cert.pem
        - /certificates/{{ env "REMOTE_KME_ID" }}/rest/rest.ca-chain.cert.pem
        # Allow only local SAE client CA chain
        - /certificates/{{ env "LOCAL_KME_ID" }}/sae/sae.ca-chain.cert.pem
        clientAuthType: RequireAndVerifyClientCert
  stores:
    default:
      defaultCertificate:
        # Used when no Server Name Indication (SNI) is provided
        certFile: /certificates/{{ env "LOCAL_KME_ID" }}/rest/rest.ca-chain.cert.pem
        keyFile: /certificates/{{ env "LOCAL_KME_ID" }}/rest/rest.key.pem
