#!/bin/bash
# Rotates logs generated by Vault audit
#
# To trigger log rotation, run this script periodically via cron
# e.g. '*/5 * * * * {{ env "LOCAL_REPO_DIRPATH" }}/volumes/{{ env "LOCAL_KME_ID" }}/vault/logs/logrotate.sh'

cd "$(dirname "$0")" && /usr/sbin/logrotate logrotate.conf --state logrotate.state

