# Traefik static configuration file

global:
  checkNewVersion: True
  sendAnonymousUsage: False

log:
  level: INFO
  format: common
  # Uncomment to dump to log file instead of to stdout
  # where Docker picks it up.
  #filePath: /var/log/traefik/traefik.log

accessLog:
  format: common
  # Uncomment to dump access logs to file
  #filePath: /var/log/traefik/access.log

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: True

  websecure:
    address: :443

providers:
  docker:
    swarmMode: False
    exposedByDefault: False
    network: traefik-public
    watch: True

  file:
    directory: /etc/traefik/traefik.d/
    watch: True
